/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ufjf.mips.ui;

import com.ufjf.mips.utils.FileManager;
import com.ufjf.mips.utils.FileValidator;
import java.io.BufferedReader;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nova
 */
public class FileSelector extends javax.swing.JFrame {
    
    FileValidator validador;
    
    /** Creates new form FileSelector */
    public FileSelector() {
        initComponents();
        
        configurarRadioGroup();
        
        validador = new FileValidator();
                
        this.setLocationRelativeTo(null);
        
        configurarSeletor();
    }

    private void configurarRadioGroup() {
        group.add(jRadioButton1);
        group.add(jRadioButton2);
    }

    private void configurarSeletor() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo de texto (.txt)", "txt");
        seletorDeArquivo.setFileFilter(filter);
        seletorDeArquivo.setAcceptAllFileFilterUsed(false); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        seletorDeArquivo = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        buscaPorTextoField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        selecionarArquivoButton = new javax.swing.JButton();
        loadArquivoButton = new javax.swing.JButton();
        buscaComputadorField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        seletorDeArquivo.setDialogTitle("Selecionar arquivo MIPS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecione arquivo (.txt) para carregamento");
        setResizable(false);

        buscaPorTextoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaPorTextoFieldActionPerformed(evt);
            }
        });

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Digitar nome do arquivo (pasta exampleFiles)");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Abrir arquivo no computador");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        selecionarArquivoButton.setText("Abrir");
        selecionarArquivoButton.setEnabled(false);
        selecionarArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoButtonActionPerformed(evt);
            }
        });

        loadArquivoButton.setText("Carregar");
        loadArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadArquivoButtonActionPerformed(evt);
            }
        });

        buscaComputadorField.setEditable(false);
        buscaComputadorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaComputadorFieldActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrada via teclado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1)
                    .addComponent(buscaPorTextoField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(43, 43, 43)
                        .addComponent(selecionarArquivoButton))
                    .addComponent(buscaComputadorField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loadArquivoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscaPorTextoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(selecionarArquivoButton))
                .addGap(18, 18, 18)
                .addComponent(buscaComputadorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadArquivoButton)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaPorTextoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaPorTextoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaPorTextoFieldActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       buscaComputadorField.setEnabled(false);
       buscaPorTextoField.setEnabled(true);
       selecionarArquivoButton.setEnabled(false);
       buscaComputadorField.setText("");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       buscaComputadorField.setEnabled(true);
       buscaPorTextoField.setEnabled(false);
       selecionarArquivoButton.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void buscaComputadorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaComputadorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaComputadorFieldActionPerformed

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void loadArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadArquivoButtonActionPerformed

        try {
            String localArquivo;
            if(jRadioButton1.isSelected()){
                localArquivo = "exampleFiles/" + buscaPorTextoField.getText();
               
            } else {
               localArquivo = buscaComputadorField.getText();
            }
            validador.validarArquivo(localArquivo);
             new MipsForm(FileManager.criarListaComandos(localArquivo));
             this.setVisible(false);
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(),
                    "Erro!",0);
        }
    }//GEN-LAST:event_loadArquivoButtonActionPerformed

    private void selecionarArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoButtonActionPerformed
    int returnVal = seletorDeArquivo.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = seletorDeArquivo.getSelectedFile();
        buscaComputadorField.setText(file.getAbsolutePath());
    }
    }//GEN-LAST:event_selecionarArquivoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KeyboardInput input = new KeyboardInput();
        input.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscaComputadorField;
    private javax.swing.JTextField buscaPorTextoField;
    private javax.swing.ButtonGroup group;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton loadArquivoButton;
    private javax.swing.JButton selecionarArquivoButton;
    private javax.swing.JFileChooser seletorDeArquivo;
    // End of variables declaration//GEN-END:variables

}
